# see conda-forge.yaml#/noarch_platforms which controls the platforms
noarch_platform:
  - 'unix'  # [linux]
  - 'win'  # [win]
pywin32_python:
  - 'pypy'  # [win]
  - 'not-pypy'  # [win]
channel_targets:
  - conda-forge pywin32_on_windows_experimental
